### ISSUE TITLE
Issue with installation via Conda

### ISSUE THREAD

**Issue by apoorav-singh** [quartiq/highfinesse-net#2]
I had issue installing this package via Conda.  Error message is as such:

> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - highfinesse-net
> 
> Current channels:
> 
>   - https://repo.anaconda.com/pkgs/main/win-64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/r/win-64
>   - https://repo.anaconda.com/pkgs/r/noarch
>   - https://repo.anaconda.com/pkgs/msys2/win-64
>   - https://repo.anaconda.com/pkgs/msys2/noarch
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.

OS: Windows 10
python: 3.9.12
Conda: 4.14.0

Let me know if there is some other installation technique.

**Comment by jordens** [comment]
basic `setup.py install` and pip could work.
But this is an unmaintained library to a research project device that has not been and likely never will be available anywhere.
Closing as inapplicable.
